### ISSUE TITLE
Gather feedback

### ISSUE THREAD

**Issue by lunohodov** [lunohodov/awesome-astrophotography#3]
This issue acts as a feedback placeholder for including `awesome-astrophotography` to the [awesome tree](https://github.com/sindresorhus/awesome).

Please use the corresponding [pull request](https://github.com/lunohodov/awesome-astrophotography/pull/4) to provide actual feedback and suggestions.

Thank you ❤️

**Comment by Jogai** [comment]
My only exposure (hehe...) to astrophotograpy is that I follow this guy: https://twitter.com/AJamesMcCarthy/status/1350570367681658880

**Comment by lunohodov** [comment]
@Jogai You should check the other resources here 😉
